id: P0984B027
initial_creation_type: ocr
source_metadata:
  volumes:
    99924b44e52049629eb29bea31ae2477:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: སྐྱེ་མེད་རིན་པོ་ཆེའི་མཛོད།
      total_pages: 1605
      volume_number: 57
